import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css"; // 导入Bootstrap CSS
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";
// 导入Inter字体
const inter = Inter({ subsets: ["latin"] });
// 配置页面元数据
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapClient /> {/* 引入Bootstrap客户端组件 */}
        {children}
      </body>
    </html>
  );
}